# Generated by Django 4.2 on 2024-03-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OctoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostname', models.CharField(max_length=200)),
                ('Ip', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'octo',
                'ordering': ['id'],
            },
        ),
    ]
